#!/usr/bin/env python3
"""Regenerate src/assets/demo_sprite.c — 64x64 ARGB8888 radial-gradient sprite.

Stored in repo so the M2c demo has a deterministic test image without
shelling out to an image library at build time. Re-run only when the
look needs to change."""
import math, os, sys

W, H = 64, 64
out = []
cx, cy = (W - 1) / 2, (H - 1) / 2
maxd = math.hypot(cx, cy)
for y in range(H):
    for x in range(W):
        d = math.hypot(x - cx, y - cy) / maxd
        ang = math.atan2(y - cy, x - cx)
        ring = 0.5 + 0.5 * math.sin(ang * 5)
        t = max(0.0, 1.0 - d)
        a = int(255 * (t ** 0.7))
        r = int(255 * (1 - d) * (0.4 + 0.6 * ring))
        g = int(80 + 150 * d)
        b = int(255 * d * (0.6 + 0.4 * (1 - ring)))
        r = max(0, min(255, r)); g = max(0, min(255, g)); b = max(0, min(255, b))
        out += [b, g, r, a]  # LVGL ARGB8888 = B,G,R,A in memory

dst = os.path.join(os.path.dirname(__file__), "..", "src", "assets", "demo_sprite.c")
dst = os.path.normpath(dst)
with open(dst, "w") as f:
    f.write("/* Auto-generated by scripts/gen_demo_image.py — DO NOT EDIT BY HAND. */\n")
    f.write("/* 64x64 ARGB8888 radial-gradient sprite for M2c IMAGE demo. */\n")
    f.write('#include "lvgl.h"\n\n')
    f.write("static const uint8_t demo_sprite_data[] = {\n")
    for i in range(0, len(out), 16):
        f.write("    " + ", ".join(f"0x{b:02X}" for b in out[i:i+16]) + ",\n")
    f.write("};\n\n")
    f.write("const lv_image_dsc_t demo_sprite = {\n")
    f.write("    .header = {\n")
    f.write("        .magic = LV_IMAGE_HEADER_MAGIC,\n")
    f.write("        .cf = LV_COLOR_FORMAT_ARGB8888,\n")
    f.write(f"        .w = {W},\n")
    f.write(f"        .h = {H},\n")
    f.write(f"        .stride = {W*4},\n")
    f.write("    },\n")
    f.write(f"    .data_size = {len(out)},\n")
    f.write("    .data = demo_sprite_data,\n")
    f.write("};\n")
print(f"wrote {dst}", file=sys.stderr)
